# creating the build file (dist/) for nginx to server

FROM node:20-alpine AS builder

WORKDIR /todo-app/frontend

COPY package*.json ./

RUN npm ci 

COPY . .

RUN npm run build

# creating the nginx image using the build file only form 'builder'

FROM nginx:1.27-alpine

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf 
COPY --from=builder /todo-app/frontend/dist /usr/share/nginx/html

EXPOSE 80